'use strict';

window.FLITS_DATA = {
  lessons: [
    lesson(
      'taal-inleiding',
      'Taal-inleiding',
      'Basis',
      ['taal', 'taalniveaus', 'analyse'],
      'Taal is het systeem waarmee betekenis wordt gedeeld. In toetsantwoorden orden je taal altijd via inhoud, vorm en gebruik.',
      'Taal bestaat uit meerdere lagen: semantiek, morfologie, syntaxis, fonologie en pragmatiek. Een sterke conclusie benoemt welke laag sterk of zwak is.',
      ['verschil taal versus spraak', 'inhoud-vorm-gebruik', 'semantiek', 'morfosyntaxis', 'pragmatiek'],
      'Een kind gebruikt veel woorden, maar vertelt onsamenhangend en maakt korte zinnen. Waarom is “woordenschat is prima” geen volledige conclusie?',
      'Leg in 45 seconden uit hoe je een taalprofiel ordent.',
      'Ik orden taal niet alleen op aantal woorden, maar op inhoud, vorm en gebruik. Woordenschat hoort bij semantiek, zinsbouw bij morfosyntaxis en functioneren in gesprek bij pragmatiek. Zo voorkom ik dat één sterk onderdeel zwakke taalniveaus maskeert.',
      ['taal', 'inhoud', 'vorm', 'gebruik', 'semantiek', 'morfosyntaxis', 'pragmatiek']
    ),
    lesson(
      'taalontwikkeling-inleiding',
      'Taalontwikkeling - inleiding',
      'Ontwikkeling',
      ['mijlpalen', 'leeftijd', 'normaal-afwijkend'],
      'Normale taalontwikkeling geeft je vergelijkingslat: je koppelt gedrag aan leeftijd, fase, begrip, productie en context.',
      'Begrip loopt vaak voor op productie. Je moet kunnen uitleggen of taalgedrag passend, vertraagd of afwijkend is.',
      ['prelinguale fase', 'vroeglinguale fase', 'differentiatie', 'voltooiingsfase', 'begrip vóór productie'],
      'Een kind van 4 jaar gebruikt vooral tweewoordzinnen. Welke ontwikkelingsvergelijking maak je voordat je een conclusie trekt?',
      'Leg uit waarom leeftijd altijd nodig is bij interpretatie van taalgedrag.',
      'Leeftijd bepaalt of gedrag nog ontwikkelingspassend is. Een korte zin kan bij een jong kind normaal zijn, maar bij een ouder kind wijzen op vertraging of stoornis. Daarom koppel ik elke observatie aan fase, begrip, productie en dagelijks functioneren.',
      ['leeftijd', 'fase', 'ontwikkeling', 'begrip', 'productie']
    ),
    lesson(
      'spraakontwikkeling-inleiding',
      'Spraakontwikkeling - inleiding',
      'Spraak',
      ['spraakontwikkeling', 'verstaanbaarheid', 'processen'],
      'Spraakontwikkeling gaat over het leren maken en organiseren van klanken. Vereenvoudigingen zijn normaal tot ze te lang blijven of verstaanbaarheid sterk beperken.',
      'Je kijkt naar leeftijd, verstaanbaarheid, processen, consistentie en stimulabiliteit voordat je een stoornis of behandelroute kiest.',
      ['verstaanbaarheid', 'fonologische processen', 'leeftijdsnorm', 'consistentie', 'stimulabiliteit'],
      'Een kind van 5 zegt “tee” voor “kees” en laat clusters weg. Wat benoem je en waarom is leeftijd belangrijk?',
      'Leg uit hoe normale spraakontwikkeling helpt bij je diagnostische conclusie.',
      'Ik benoem eerst welke processen ik hoor, zoals fronting of clusterreductie, en koppel die aan leeftijd en verstaanbaarheid. Als processen hardnekkig zijn of participatie beperken, wordt behandeling gericht op functionele contrasten en generalisatie.',
      ['spraak', 'verstaanbaarheid', 'fronting', 'clusterreductie', 'leeftijd', 'stimulabiliteit']
    ),
    lesson(
      'spraak-inleiding',
      'Spraak - Inleiding',
      'Spraak',
      ['fonetiek', 'fonologie', 'planning'],
      'Spraak is de hoorbare uitvoering van taal via adem, stem, resonantie, articulatie en motorische planning.',
      'Een toetswaardig antwoord onderscheidt fonetisch, fonologisch en spraakmotorisch. Niet elke uitspraakfout vraagt dezelfde behandeling.',
      ['fonetisch versus fonologisch', 'motorische uitvoering', 'planning/programmering', 'Levelt als denkkader'],
      'Een kind zegt “toek” voor “koek”, maar kan /k/ soms nazeggen. Waarom is dat belangrijk?',
      'Leg het verschil uit tussen fonetisch, fonologisch en planning.',
      'Bij een fonetisch probleem lukt de motorische klankvorming onvoldoende. Bij een fonologisch probleem gebruikt het kind het klankcontrast niet goed. Bij planning of VOD zie je vaak wisselende fouten en zoekgedrag. Daarom onderzoek ik stimulabiliteit, contrast en consistentie.',
      ['fonetisch', 'fonologisch', 'planning', 'consistentie', 'contrast', 'stimulabiliteit']
    ),
    lesson(
      'diagnostiek-pragmatiek',
      'Diagnostiek pragmatiek',
      'Diagnostiek',
      ['pragmatiek', 'observatie', 'context'],
      'Pragmatiek diagnosticeer je niet alleen met een test. Het gaat om taalgebruik in echte interactie.',
      'Kijk naar beurtwisseling, topic, luisteraaraanpassing, perspectief nemen, herstelgedrag en narratieve samenhang.',
      ['beurtwisseling', 'perspectief nemen', 'topic management', 'verhaalstructuur', 'contextobservatie'],
      'Een kind scoort gemiddeld op taaltests, maar vertelt chaotisch en houdt geen rekening met de luisteraar. Wat onderzoek je?',
      'Leg uit waarom pragmatiek altijd contextobservatie vraagt.',
      'Pragmatiek beoordeel ik in interactie, omdat het gaat om taalgebruik met anderen. Ik combineer testgegevens met ouder- en leerkrachtinformatie en observatie van beurtwisseling, contextinformatie, perspectief en verhaalopbouw.',
      ['pragmatiek', 'beurtwisseling', 'context', 'observatie', 'narratief', 'luisteraar']
    ),
    lesson(
      'diagnostiek-fonetiek-fonologie',
      'Diagnostiek Fonetiek - fonologie',
      'Diagnostiek',
      ['fonetiek', 'fonologie', 'spraakonderzoek'],
      'Bij spraakdiagnostiek zoek je uit of de fout motorisch, fonologisch of spraakmotorisch/planning is.',
      'Onderzoek productie, stimulabiliteit, contrast, consistentie, fonologische processen en impact op verstaanbaarheid.',
      ['fonetisch', 'fonologisch', 'contrast', 'stimulabiliteit', 'minimale paren', 'consistentie'],
      'Een kind vervangt /k/ door /t/. Welke drie checks bepalen of je fonologisch of fonetisch denkt?',
      'Leg uit hoe je diagnostiek inzet om methodekeuze te onderbouwen.',
      'Ik check of het kind de klank motorisch kan maken, of het contrast betekenisvol gebruikt en of fouten consistent zijn. Daardoor kan ik onderscheid maken tussen fonetische uitvoering, fonologische representatie en planning. Dat stuurt direct de behandelkeuze.',
      ['fonetisch', 'fonologisch', 'contrast', 'stimulabiliteit', 'minimale paren', 'consistentie']
    ),
    lesson(
      'behandeling-fonetiek-fonologie',
      'Behandeling Fonetiek - fonologie',
      'Behandeling',
      ['methode', 'contrast', 'generalisatie'],
      'Behandeling begint niet bij “klank oefenen”, maar bij het probleemmechanisme: motorisch maken, klankcontrast leren of spraakplanning automatiseren.',
      'Fonetisch behandelen richt zich op articulatieplaats en beweging. Fonologisch behandelen richt zich op betekenisvolle contrasten, perceptie-productie en generalisatie.',
      ['stimulabiliteit', 'contrast', 'minimale paren', 'auditieve discriminatie', 'generalisatie'],
      'Een kind zegt /t/ voor /k/ en hoort het verschil nog niet. Welke behandelstap komt vóór spontaan spreken?',
      'Verdedig je methodekeuze bij een fonologisch proces.',
      'Ik start met het kind laten ervaren dat /k/ en /t/ betekenisverschil geven. Met minimale paren en auditieve discriminatie werk ik aan het fonologische contrast. Als de klank met hulp lukt, bouw ik door naar woorden, zinnen en gebruik in de klas.',
      ['contrast', 'stimulabiliteit', 'minimale paren', 'auditieve discriminatie', 'generalisatie']
    ),
    lesson(
      'behandeling-pragmatiek',
      'Behandeling - pragmatiek',
      'Behandeling',
      ['pragmatiek', 'narratief', 'transfer'],
      'Pragmatische behandeling richt zich op communicatie in context: beurtgedrag, perspectief, herstelstrategieën en verhalen vertellen.',
      'Een sterk plan traint niet alleen in de behandelkamer, maar plant transfer naar spel, klas en thuis.',
      ['beurtwisseling', 'joint attention', 'perspectief nemen', 'verhaalopbouw', 'ouders en school'],
      'Een kind vertelt zonder begin-midden-einde en reageert niet op vragen van de ander. Formuleer één functioneel behandeldoel.',
      'Leg uit hoe je pragmatiek behandelt zonder losse sociale trucjes.',
      'Ik behandel pragmatiek functioneel: wat moet het kind in echte interactie beter kunnen? Ik oefen bijvoorbeeld beurtwisseling of verhaalopbouw in spel, gebruik modeling en visuele steun, en betrek ouders of leerkracht zodat het gedrag ook buiten therapie geoefend wordt.',
      ['pragmatiek', 'narratief', 'beurtwisseling', 'perspectief', 'ouders', 'school']
    ),
    lesson(
      'omft-deel-4',
      'Flitscollege wk2 - Deel 4. OMFT',
      'Mondgebied',
      ['OMFT', 'mondgewoonten', 'functie'],
      'OMFT gaat over afwijkende mondgewoonten en spierbalans: rustpositie, lipsluiting, slikken, tongpositie en invloed op spraak/gebit.',
      'Je onderscheidt structuur en functie en weet wanneer samenwerking met tandarts of orthodontist nodig is.',
      ['open beet', 'tongpersen', 'mondademen', 'lipsluiting', 'slikpatroon', 'orthodontist'],
      'Een kind slist en heeft een open beet door duimzuigen. Waarom start je niet alleen met /s/-training?',
      'Leg uit waarom OMFT soms voorwaarde is voor spraaktherapie.',
      'Bij afwijkende mondgewoonten behandel ik niet alleen de klank. Een open beet of tongpers kan de articulatie blijven verstoren. Daarom kijk ik naar rustpositie, slik, lipsluiting en gewoonteafbouw, en stem ik zo nodig af met tandarts of orthodontist.',
      ['omft', 'open beet', 'tong', 'slikken', 'mondgewoonte', 'orthodontist']
    ),
    lesson(
      'structureren-functies',
      'Flitscollege wk2 - Deel 1. Structureren en functies',
      'Mondgebied',
      ['structuur', 'functie', 'onderzoek'],
      'Bij mondgebied kijk je systematisch: eerst structuren, dan functies. Zo voorkom je dat je een spraakklacht los van anatomie of mondgedrag beoordeelt.',
      'Structuur is wat je ziet aan lippen, tong, kaak, gehemelte en gebit. Functie is wat ermee gebeurt: ademen, rusthouding, slikken, kauwen en spreken.',
      ['structuuronderzoek', 'functieonderzoek', 'rustpositie', 'lipsluiting', 'tongfunctie'],
      'Een kind heeft open mondgedrag en onduidelijke articulatie. Welke structuur- en functiepunten observeer je?',
      'Leg uit waarom structuur en functie allebei nodig zijn in je analyse.',
      'Ik beschrijf eerst de structuren, zoals gebit, lippen, tong en gehemelte. Daarna beoordeel ik functies zoals rustpositie, lipsluiting, slikken en spreken. De combinatie bepaalt of het spraakprobleem mede door mondmotoriek of mondgewoonten wordt onderhouden.',
      ['structuuronderzoek', 'functieonderzoek', 'rustpositie', 'lipsluiting', 'tong', 'slikken']
    ),
    lesson(
      'testleer',
      'Testleer',
      'Diagnostiek',
      ['testleer', 'normscore', 'betrouwbaarheid'],
      'Tests geven meetgegevens, geen absolute waarheid. Je conclusie hangt af van standaardisatie, validiteit, betrouwbaarheid, normering en context.',
      'Een losse normscore is nooit genoeg. Combineer score, betrouwbaarheidsinterval, observatie, hulpvraag en dagelijks functioneren.',
      ['normgroep', 'standaardisatie', 'validiteit', 'betrouwbaarheid', 'betrouwbaarheidsinterval', 'observatie'],
      'Een kind scoort laag op één test, maar was moe en functioneert wisselend. Hoe formuleer je voorzichtig?',
      'Leg uit waarom je een testscore niet als harde waarheid rapporteert.',
      'Ik rapporteer een testscore als meetgegeven met bandbreedte. Door betrouwbaarheidsinterval, observatie, standaardisatie en dagelijks functioneren mee te nemen voorkom ik overconclusies. Een lage score ondersteunt de hypothese, maar bewijst op zichzelf geen stoornis.',
      ['normscore', 'betrouwbaarheidsinterval', 'validiteit', 'betrouwbaarheid', 'observatie', 'context']
    ),
    lesson(
      'semantiek-inleiding',
      'Semantiek - inleiding',
      'Taalniveaus',
      ['semantiek', 'woordenschat', 'lexicon'],
      'Semantiek gaat over betekenis, woordenschat, woordrelaties en woordvinding.',
      'Niet alleen hoeveel woorden telt, maar hoe rijk woorden zijn opgeslagen en gebruikt.',
      ['receptieve woordenschat', 'actieve woordenschat', 'woordvinding', 'categoriseren', 'semantisch netwerk'],
      'Een kind kent een woord bij aanwijzen, maar gebruikt het niet spontaan. Wat betekent dat voor je analyse?',
      'Leg uit hoe je woordenschat niet als woordenlijst maar als netwerk behandelt.',
      'Ik kijk bij woordenschat naar begrip, productie en kwaliteit van opslag. Een woord alleen herkennen is iets anders dan het actief gebruiken. Daarom behandel ik woorden in betekenisrelaties, categorieën, context en herhaalde functionele toepassing.',
      ['semantiek', 'woordenschat', 'receptief', 'productief', 'netwerk', 'woordvinding']
    ),
    lesson(
      'morfologie-syntaxis-inleiding',
      'Morfologie en Syntaxis, inleiding',
      'Taalniveaus',
      ['morfologie', 'syntaxis', 'zinsontwikkeling'],
      'Morfologie gaat over woordvormen; syntaxis over zinsbouw. Samen vormen ze de grammaticale laag van taal.',
      'Analyseer zinslengte, woordvolgorde, werkwoordsvormen, functiewoorden en complexiteit.',
      ['woordvolgorde', 'werkwoordvervoeging', 'functiewoorden', 'zinslengte', 'samengestelde zinnen'],
      'Een kind zegt “papa auto rijden”. Welke morfosyntactische doelen passen net boven niveau?',
      'Leg uit hoe je van zwakke zinsontwikkeling naar een SMART behandeldoel gaat.',
      'Bij morfosyntaxis kijk ik naar woordvolgorde, woordvormen en functiewoorden. Een passend doel ligt net boven het huidige niveau, bijvoorbeeld een S-V-O-structuur in spelcontext. Via modeling, recasting en scaffolding bouw ik steun geleidelijk af.',
      ['morfosyntaxis', 'woordvolgorde', 'werkwoord', 'zinsbouw', 'scaffolding', 'recasting']
    ),
    lesson(
      'pragmatiek-inleiding',
      'Pragmatiek, inleiding',
      'Taalgebruik',
      ['pragmatiek', 'interactie', 'narratief'],
      'Pragmatiek is taalgebruik in context: beurtwisseling, perspectief, onderwerp, informatie voor de luisteraar en verhalen vertellen.',
      'Een kind kan woorden en zinnen kennen, maar toch communicatief vastlopen doordat het taalgebruik niet past bij de situatie.',
      ['beurtwisseling', 'perspectief nemen', 'topic management', 'verhaalstructuur', 'luisteraaraanpassing'],
      'Een kind geeft antwoorden die niet aansluiten op de vraag en vertelt zonder samenhang. Welke pragmatische onderdelen benoem je?',
      'Leg uit waarom pragmatiek de brug is naar communicatieve redzaamheid.',
      'Pragmatiek bepaalt of taal werkt in contact met anderen. Ik kijk naar beurtwisseling, onderwerp vasthouden, perspectief nemen en verhaalopbouw. Daardoor kan ik uitleggen wat het kind nodig heeft om thuis of in de klas communicatief redzamer te worden.',
      ['pragmatiek', 'beurtwisseling', 'narratief', 'context', 'luisteraar', 'participatie']
    ),
    lesson(
      'model-van-levelt',
      'Model van Levelt',
      'Klinisch redeneren',
      ['Levelt', 'formulator', 'articulator'],
      'Levelt helpt je fouten plaatsen: intentie, taalkundige formulering, motorische uitvoering en monitoring zijn verschillende schakels.',
      'Een 10-student zegt niet alleen “uitspraakfout”, maar redeneert: zit het in fonologische keuze, planning, articulatie of monitoring?',
      ['conceptualiseerder', 'formulator', 'articulator', 'zelfmonitoring', 'fonologisch versus fonetisch'],
      'Een kind zegt hetzelfde woord soms goed en soms fout. Waar in Levelt kan het misgaan?',
      'Gebruik Levelt om fonologisch, fonetisch en planning van elkaar te onderscheiden.',
      'Ik plaats de fout in Levelt: de conceptualiseerder gaat over de boodschap, de formulator over woorden en klankvorm, de articulator over motorische uitvoering en monitoring over zelfcontrole. Zo onderzoek ik gericht of het probleem in taalvorm, klankcontrast, planning of uitvoering zit.',
      ['levelt', 'formulator', 'articulator', 'fonologisch', 'fonetisch', 'planning', 'consistentie']
    ),
    lesson(
      'tandheelkunde-deel-2',
      'Flitscollege wk2- Deel 2. Tandheel...',
      'Mondgebied',
      ['tandheelkunde', 'occlusie', 'gebit'],
      'Tandheelkundige informatie helpt verklaren waarom articulatie of mondfunctie door gebit, kaakstand of occlusie beïnvloed wordt.',
      'Je hoeft geen tandarts te zijn, maar moet weten wanneer occlusie, open beet, wisselfase of orthodontie relevant is voor logopedie.',
      ['occlusie', 'open beet', 'wisselgebit', 'tongpersen', 'orthodontist', 'samenwerking'],
      'Een kind heeft interdentaliteit en een open beet. Welke tandheelkundige informatie wil je en waarom?',
      'Leg uit hoe tandheelkundige factoren je logopedische plan beïnvloeden.',
      'Ik koppel de articulatiefout aan de mondstructuur. Een open beet of afwijkende occlusie kan de tongpositie en /s/-productie beïnvloeden. Daarom behandel ik mondfunctie en werk ik samen met tandarts of orthodontist wanneer de gebitsfactor het logopedisch resultaat kan beperken.',
      ['tandheelkunde', 'occlusie', 'open beet', 'tong', 'orthodontist', 'samenwerking']
    ),
    lesson(
      'diagnostiek-meertaligheid',
      'Logopedische diagnostiek bij meer...',
      'Differentiaaldiagnostiek',
      ['meertaligheid', 'NT2', 'TOS'],
      'Bij meertaligheid is een lage Nederlandse score geen automatisch bewijs voor TOS.',
      'Kijk naar taalaanbod, thuistaal, leerbaarheid, functioneren in beide talen en cultuursensitieve interpretatie.',
      ['taalaanbod per taal', 'thuistaalinformatie', 'leerbaarheid', 'uitval in beide talen', 'cultuursensitief interpreteren'],
      'Een Pools-Nederlands kind scoort laag op Nederlandse woordenschat. Welke informatie mis je voor een TOS-conclusie?',
      'Leg uit waarom Nederlandse normscores bij meertaligheid voorzichtig geïnterpreteerd worden.',
      'Bij een meertalig kind interpreteer ik lage Nederlandse scores in relatie tot aanbod en thuistaalontwikkeling. TOS wordt waarschijnlijker als er hardnekkige uitval in beide talen is en beperkte groei ondanks passend aanbod. Daarom vraag ik thuistaalinformatie, leerbaarheid en context uit.',
      ['meertalig', 'nt2', 'tos', 'thuistaal', 'aanbod', 'leerbaarheid']
    ),
    lesson(
      'inleiding-spraaktaalstoornissen',
      'Deel A Inleiding spraaktaalstoornis...',
      'Stoornissen',
      ['spraaktaalstoornis', 'differentiaal', 'functioneren'],
      'Een spraaktaalstoornis beschrijf je niet als losse fout, maar als profiel met oorzaak, ernst, hardnekkigheid en gevolg voor functioneren.',
      'Je differentieert tussen taal, spraak, gehoor, cognitie, motoriek, aanbod, meertaligheid en sociaal-emotionele factoren.',
      ['taalprofiel', 'spraakprofiel', 'differentiaaldiagnose', 'hardnekkigheid', 'dagelijks functioneren'],
      'Een kind heeft lage zinsontwikkeling én gehoorproblemen. Waarom is één label nu te snel?',
      'Geef een toetswaardige startzin voor een spraaktaalstoornis.',
      'Ik beschrijf eerst het profiel: welke taal- en spraakonderdelen vallen uit, hoe hardnekkig is dat en wat betekent het voor activiteit en participatie? Daarna weeg ik alternatieve of bijkomende verklaringen zoals gehoor, cognitie, motoriek, aanbod en meertaligheid.',
      ['taal', 'spraak', 'hardnekkig', 'functioneren', 'differentiaal', 'gehoor', 'cognitie']
    ),
    lesson(
      'richtlijn-tos',
      'Richtlijn Logopedie bij TOS tbv',
      'TOS',
      ['richtlijn', 'TOS', 'behandelplan'],
      'De TOS-richtlijn helpt je onderbouwen: TOS vraagt profielanalyse, functionele doelen, samenwerking met omgeving en evaluatie.',
      'Een sterk antwoord verbindt TOS-kenmerken aan ICF, doelen, methode, ouders/school, intensiteit en prognose.',
      ['TOS', 'ICF', 'functionele doelen', 'ouders en school', 'evaluatie', 'prognose'],
      'Een kind met TOS oefent goed in therapie maar gebruikt taal niet in de klas. Wat ontbreekt in je behandelplan?',
      'Leg uit hoe je richtlijnmatig denkt bij TOS.',
      'Bij TOS werk ik niet alleen aan losse taalvormen, maar aan communicatieve redzaamheid. Ik formuleer doelen op ICF-niveau, kies een passende methode, betrek ouders en school voor transfer en evalueer of de vaardigheid in dagelijks functioneren zichtbaar wordt.',
      ['richtlijn', 'tos', 'icf', 'participatie', 'ouders', 'school', 'evaluatie', 'prognose']
    ),
    lesson(
      'plagiaat-apa',
      'Plagiaat en APA',
      'Studievaardigheid',
      ['APA', 'bronvermelding', 'eigen woorden'],
      'In toets- en verslagwerk moet je laten zien dat je bronnen begrijpt en professioneel verwerkt. Kopiëren is geen klinisch redeneren.',
      'Gebruik eigen woorden, verwijs volgens APA en koppel elke bron aan jouw casuskeuze of behandelargument.',
      ['plagiaat vermijden', 'parafraseren', 'APA in tekst', 'literatuurlijst', 'bron naar toepassing'],
      'Je gebruikt een boekpassage over scaffolding in een behandelplan. Hoe voorkom je plagiaat én maak je het toetsgericht?',
      'Leg uit hoe brongebruik je mondelinge verantwoording sterker maakt.',
      'Ik parafraseer de bron in eigen woorden, verwijs volgens APA en koppel de theorie direct aan mijn casus. Bijvoorbeeld: scaffolding onderbouwt waarom ik tijdelijke visuele steun geef en die afbouw zodra het kind zelfstandiger wordt. Zo wordt brongebruik klinische verantwoording.',
      ['plagiaat', 'apa', 'bronvermelding', 'parafraseren', 'toepassing', 'casus']
    )
  ]
};

function lesson(id, title, domain, tags, summary, snap, memory, caseQuestion, oralPrompt, model, checks) {
  return { id, title, domain, tags, summary, snap, memory, caseQuestion, oralPrompt, model, checks };
}
