'use strict';

window.FLITS_DATA = {
  lessons: [
    lesson(
      'basis-taal-spraak',
      '1. Taal, spraak en taalniveaus',
      'Basis',
      ['taal', 'spraak', 'taalniveaus'],
      'Taal is het regelsysteem waarmee betekenis wordt gedeeld; spraak is de hoorbare uitvoering via klanken. Analyseer altijd inhoud, vorm en gebruik.',
      'Je moet taal en spraak uit elkaar houden en per taalniveau kunnen zeggen wat je ziet: fonologie, semantiek, morfosyntaxis en pragmatiek.',
      ['verschil taal versus spraak', 'begrip versus productie', 'inhoud-vorm-gebruik', 'fonologie, semantiek, morfosyntaxis en pragmatiek'],
      'Een kind gebruikt veel woorden, maar maakt korte zinnen en vertelt onsamenhangend. Waarom is “woordenschat is prima” geen volledige conclusie?',
      'Leg in 60 seconden uit hoe je een taalprofiel ordent in inhoud, vorm en gebruik.',
      'Ik orden het taalprofiel niet alleen op aantal woorden, maar op inhoud, vorm en gebruik. Woordenschat hoort bij semantiek, zinsbouw bij morfosyntaxis en functioneren in gesprek bij pragmatiek. Zo voorkom ik dat één sterk onderdeel zwakke taalniveaus maskeert.',
      ['taal', 'spraak', 'inhoud', 'vorm', 'gebruik', 'morfosyntaxis', 'pragmatiek']
    ),
    lesson(
      'ontwikkeling-fasen',
      '2. Normale taalontwikkeling en fasen',
      'Ontwikkeling',
      ['mijlpalen', 'leeftijd', 'normaal-afwijkend'],
      'Normale ontwikkeling geeft je de lat: je vergelijkt casusgedrag altijd met leeftijd, fase en context.',
      'Begrip loopt vaak vóór productie. Je moet kunnen uitleggen wanneer een fout passend, vertraagd of afwijkend is.',
      ['prelinguale fase', 'vroeglinguale fase', 'differentiatie', 'voltooiingsfase', 'begrip vóór productie'],
      'Een kind van 4 jaar is slecht verstaanbaar en gebruikt tweewoordzinnen. Welke ontwikkelingsvergelijking maak je eerst?',
      'Leg uit waarom leeftijd altijd nodig is bij interpretatie van spraak- en taalgedrag.',
      'Leeftijd bepaalt of gedrag nog ontwikkelingspassend is. Een vereenvoudiging of korte zin kan bij een jong kind normaal zijn, maar bij een ouder kind wijzen op vertraging of stoornis. Daarom koppel ik elke observatie aan fase, begrip, productie en dagelijks functioneren.',
      ['leeftijd', 'fase', 'ontwikkeling', 'begrip', 'productie']
    ),
    lesson(
      'voorwaarden',
      '3. Voorwaarden voor taal- en spraakontwikkeling',
      'Ontwikkeling',
      ['gehoor', 'cognitie', 'motoriek', 'omgeving'],
      'Taalontwikkeling vraagt meer dan taal: gehoor, cognitie, motoriek, interactie, sociaal-emotionele veiligheid en rijk taalaanbod sturen de leerbaarheid.',
      'Bij elke casus vraag je: is dit een taalprobleem zelf, of wordt taal beïnvloed door gehoor, aanbod, cognitie, motoriek of context?',
      ['gehoor als randvoorwaarde', 'cognitie en leerbaarheid', 'motoriek en planning', 'taalaanbod en interactie', 'sociaal-emotionele factoren'],
      'Een kind reageert traag op opdrachten en heeft wisselende taaltestscores. Welke randvoorwaarden wil je eerst controleren?',
      'Noem drie voorwaarden voor taalontwikkeling en vertaal ze naar diagnostische vragen.',
      'Ik controleer randvoorwaarden voordat ik een taalprobleem label. Gehoor bepaalt auditieve input, cognitie en leerbaarheid bepalen tempo en haalbaarheid, en omgeving bepaalt taalaanbod en transfer. Daarom vraag ik gericht naar gehoor, ontwikkeling, thuissituatie en schoolfunctioneren.',
      ['gehoor', 'cognitie', 'motoriek', 'omgeving', 'taalaanbod']
    ),
    lesson(
      'levelt',
      '4. Model van Levelt',
      'Klinisch redeneren',
      ['Levelt', 'formulator', 'articulator'],
      'Levelt helpt je fouten plaatsen: intentie, taalkundige formulering, motorische uitvoering en monitoring zijn verschillende schakels.',
      'Een 10-student zegt niet alleen “uitspraakfout”, maar redeneert: zit het in fonologische keuze, planning, articulatie of monitoring?',
      ['conceptualiseerder', 'formulator', 'articulator', 'zelfmonitoring', 'fonologisch versus fonetisch'],
      'Een kind zegt “toek” voor “koek”, maar kan /k/ soms nazeggen. Waar in Levelt kan het misgaan?',
      'Gebruik Levelt om fonologisch, fonetisch en planning van elkaar te onderscheiden.',
      'Als /k/ soms lukt, is een puur motorisch articulatieprobleem minder zeker. Ik plaats de fout in Levelt: mogelijk organiseert de formulator het klankcontrast onvoldoende, of is de planning/programmering wisselend. Ik onderzoek consistentie, stimulabiliteit en productie in verschillende contexten.',
      ['levelt', 'formulator', 'articulator', 'fonologisch', 'fonetisch', 'planning', 'consistentie']
    ),
    lesson(
      'methodisch-handelen',
      '5. Methodisch handelen',
      'Diagnostiek',
      ['hulpvraag', 'cyclus', 'conclusie'],
      'Methodisch handelen is de klinische route van hulpvraag naar gegevens, interpretatie, conclusie, doel, behandeling en evaluatie.',
      'Je moet steeds de lijn kunnen zeggen: gegeven -> interpretatie -> consequentie -> vervolgstap.',
      ['hulpvraag verhelderen', 'gegevens verzamelen', 'interpreteren', 'concluderen', 'behandelen en evalueren'],
      'Je hebt testscore, ouderverhaal en observatie. Hoe voorkom je dat je verslag een losse opsomming wordt?',
      'Leg de route van hulpvraag naar behandeladvies uit.',
      'Ik werk methodisch door elk gegeven te interpreteren en te verbinden aan een vervolgstap. Een score is dus niet los: ik koppel testresultaat, observatie en hulpvraag aan een conclusie, en vanuit die conclusie formuleer ik doelen, methode, samenwerking en evaluatie.',
      ['hulpvraag', 'gegevens', 'interpretatie', 'conclusie', 'doel', 'evaluatie']
    ),
    lesson(
      'testleer',
      '6. Testleer, normscores en betrouwbaarheidsinterval',
      'Diagnostiek',
      ['normscore', 'validiteit', 'betrouwbaarheid'],
      'Tests geven geen absolute waarheid. Normering, betrouwbaarheid, validiteit, standaardisatie en betrouwbaarheidsinterval bepalen hoe sterk je conclusie is.',
      'Een losse normscore is nooit genoeg. Combineer score, BI, observatie, hulpvraag en context.',
      ['normgroep', 'standaardisatie', 'validiteit', 'betrouwbaarheid', 'betrouwbaarheidsinterval', 'percentiel of SD'],
      'Een kind scoort laag op één test, maar functioneert wisselend en was moe. Hoe formuleer je voorzichtig?',
      'Leg uit waarom je een testscore niet als harde waarheid rapporteert.',
      'Ik rapporteer een testscore als meetgegeven met bandbreedte. Door betrouwbaarheidsinterval, observatie, standaardisatie en dagelijks functioneren mee te nemen voorkom ik overconclusies. Een lage score ondersteunt de hypothese, maar bewijst op zichzelf geen stoornis.',
      ['normscore', 'betrouwbaarheidsinterval', 'validiteit', 'observatie', 'context']
    ),
    lesson(
      'schlichting',
      '7. Schlichting en gestandaardiseerde afname',
      'Diagnostiek',
      ['Schlichting', 'standaardisatie', 'scoring'],
      'Bij Schlichting telt protocoltrouw: testsituatie, exacte aanbieding, neutrale intonatie, juiste start/terugkeer/afbreekregels en correcte scoring.',
      'Je moet kunnen uitleggen waarom kleine hulpjes, zoals wijzen of nadruk leggen, de validiteit aantasten.',
      ['testsituatie', 'neutrale toon', 'startpunt', 'terugkeerregel', 'afbreekregel', 'scoring'],
      'Je legt per ongeluk nadruk op een voorzetsel tijdens Taalbegrip. Wat zeg je in je verantwoording?',
      'Leg uit hoe standaardisatie de betrouwbaarheid van Schlichting beschermt.',
      'Ik bewaak standaardisatie omdat het kind anders geholpen kan worden door mijn gedrag in plaats van door eigen taalbegrip of taalproductie. Bij een procedurefout benoem ik concreet wat gebeurde en of dit de respons en betrouwbaarheid beïnvloed kan hebben.',
      ['schlichting', 'standaardisatie', 'neutraal', 'startpunt', 'afbreekregel', 'betrouwbaarheid']
    ),
    lesson(
      'meertaligheid',
      '8. Meertaligheid, NT2 en TOS',
      'Differentiaaldiagnostiek',
      ['meertaligheid', 'NT2', 'TOS'],
      'Bij meertaligheid is een lage Nederlandse score geen automatisch bewijs voor TOS. Kijk naar taalaanbod, thuistaal, leerbaarheid en functioneren in beide talen.',
      'Je moet NT2, blootstellingsachterstand en TOS zorgvuldig uit elkaar houden.',
      ['taalaanbod per taal', 'thuistaalinformatie', 'leerbaarheid', 'uitval in beide talen', 'cultuursensitief interpreteren'],
      'Een Turks-Nederlands kind scoort laag op Nederlandse woordenschat. Welke informatie mis je voor een TOS-conclusie?',
      'Leg uit waarom Nederlandse normscores bij meertaligheid voorzichtig geïnterpreteerd worden.',
      'Bij een meertalig kind interpreteer ik lage Nederlandse scores in relatie tot aanbod en thuistaalontwikkeling. TOS wordt waarschijnlijker als er hardnekkige uitval in beide talen is en beperkte groei ondanks passend aanbod. Daarom vraag ik thuistaalinformatie, leerbaarheid en context uit.',
      ['meertalig', 'nt2', 'tos', 'thuistaal', 'aanbod', 'leerbaarheid']
    ),
    lesson(
      'tos',
      '9. Taalontwikkelingsstoornis',
      'Taalstoornissen',
      ['TOS', 'hardnekkigheid', 'functioneren'],
      'TOS is een hardnekkige taalontwikkelingsstoornis die dagelijks functioneren belemmert en niet beter verklaard wordt door één andere factor.',
      'Onderbouw TOS met profiel, hardnekkigheid, functioneren en uitgesloten of meegewogen alternatieven.',
      ['taalprofiel', 'hardnekkigheid', 'dagelijks functioneren', 'differentiaaldiagnose', 'begrip en productie'],
      'Een kind scoort laag op zinsontwikkeling, maar heeft ook gehoorproblemen. Hoe voorkom je een te snelle TOS-diagnose?',
      'Geef een toetswaardige definitie van TOS en noem wat je moet uitsluiten of meewegen.',
      'Ik spreek pas voorzichtig over TOS als taalproblemen hardnekkig zijn, meerdere contexten raken en dagelijks functioneren belemmeren. Tegelijk weeg ik gehoor, cognitie, aanbod, meertaligheid en sociaal-emotionele factoren mee, zodat TOS geen label op basis van één score wordt.',
      ['tos', 'hardnekkig', 'functioneren', 'differentiaal', 'gehoor', 'cognitie']
    ),
    lesson(
      'semantiek',
      '10. Semantiek en woordenschat',
      'Taalniveaus',
      ['semantiek', 'woordenschat', 'lexicon'],
      'Semantiek gaat over betekenis, woordenschat, woordrelaties en woordvinding. Niet alleen hoeveel woorden, maar hoe rijk woorden zijn opgeslagen telt.',
      'Je moet receptief en productief kunnen onderscheiden en behandeling richten op rijke woordopslag.',
      ['receptieve woordenschat', 'actieve woordenschat', 'woordvinding', 'categoriseren', 'semantisch netwerk'],
      'Een kind kent een woord bij aanwijzen, maar gebruikt het niet spontaan. Wat betekent dat voor je analyse?',
      'Leg uit hoe je woordenschat niet als woordenlijst maar als netwerk behandelt.',
      'Ik kijk bij woordenschat naar begrip, productie en kwaliteit van opslag. Een woord alleen herkennen is iets anders dan het actief gebruiken. Daarom behandel ik woorden in betekenisrelaties, categorieën, context en herhaalde functionele toepassing.',
      ['semantiek', 'woordenschat', 'receptief', 'productief', 'netwerk', 'woordvinding']
    ),
    lesson(
      'morfosyntaxis',
      '11. Morfosyntaxis en zinsontwikkeling',
      'Taalniveaus',
      ['morfologie', 'syntaxis', 'zinsontwikkeling'],
      'Morfologie gaat over woordvormen; syntaxis over zinsbouw. Samen bepalen ze hoe een kind grammaticaal betekenis opbouwt.',
      'Analyseer zinslengte, woordvolgorde, werkwoordsvormen, functiewoorden en complexiteit.',
      ['woordvolgorde', 'werkwoordvervoeging', 'functiewoorden', 'zinslengte', 'samengestelde zinnen'],
      'Een kind zegt “papa auto rijden”. Welke morfosyntactische doelen passen net boven niveau?',
      'Leg uit hoe je van zwakke zinsontwikkeling naar een SMART behandeldoel gaat.',
      'Bij morfosyntaxis kijk ik naar woordvolgorde, woordvormen en functiewoorden. Een passend doel ligt net boven het huidige niveau, bijvoorbeeld een S-V-O-structuur in spelcontext. Via modeling, recasting en scaffolding bouw ik steun geleidelijk af.',
      ['morfosyntaxis', 'woordvolgorde', 'werkwoord', 'zinsbouw', 'scaffolding', 'recasting']
    ),
    lesson(
      'pragmatiek',
      '12. Pragmatiek en narratief',
      'Taalgebruik',
      ['pragmatiek', 'verhaal', 'interactie'],
      'Pragmatiek is taalgebruik in context: beurtwisseling, perspectief, onderwerp, informatie voor de luisteraar en verhalen vertellen.',
      'Formele taaltests kunnen redelijk zijn terwijl dagelijks communiceren toch vastloopt.',
      ['beurtwisseling', 'perspectief nemen', 'topic management', 'verhaalstructuur', 'luisteraaraanpassing'],
      'Een kind scoort gemiddeld op taaltests maar vertelt chaotisch en houdt geen rekening met de luisteraar. Wat onderzoek je?',
      'Leg uit waarom pragmatiek altijd contextobservatie vraagt.',
      'Pragmatiek beoordeel ik in interactie, omdat het gaat om taalgebruik met anderen. Ik kijk naar beurtwisseling, contextinformatie, perspectief en verhaalopbouw. Daarom combineer ik testgegevens met ouder- en leerkrachtinformatie en naturalistische observatie.',
      ['pragmatiek', 'narratief', 'beurtwisseling', 'context', 'observatie', 'luisteraar']
    ),
    lesson(
      'fonetisch-fonologisch',
      '13. Fonetisch versus fonologisch',
      'Spraak',
      ['fonetisch', 'fonologisch', 'contrast'],
      'Fonetisch gaat over motorische klankvorming; fonologisch over het klanksysteem en betekenisvolle contrasten.',
      'Behandeling verschilt: motorisch oefenen bij fonetisch, contrasten en perceptie-productie bij fonologisch.',
      ['produceerbaarheid', 'klankcontrast', 'stimulabiliteit', 'minimale paren', 'fonologische processen'],
      'Een kind vervangt /k/ door /t/, maar kan /k/ met hulp wel maken. Welke route onderzoek je?',
      'Leg het verschil uit tussen fonetisch en fonologisch behandelen.',
      'Bij een fonetisch probleem lukt de klankvorming motorisch onvoldoende; bij een fonologisch probleem is het klankcontrast onvoldoende georganiseerd. Als /k/ met hulp lukt, onderzoek ik of het kind het contrast /k/-/t/ begrijpt en gebruikt. Behandeling richt zich dan eerder op contrast en generalisatie.',
      ['fonetisch', 'fonologisch', 'contrast', 'stimulabiliteit', 'minimale paren']
    ),
    lesson(
      'processen',
      '14. Fonologische vereenvoudigingsprocessen',
      'Spraak',
      ['fronting', 'stopping', 'clusterreductie'],
      'Kinderen vereenvoudigen spraak via processen. Leeftijd, verstaanbaarheid, consistentie en impact bepalen of het passend of zorgelijk is.',
      'Je moet processen benoemen en meteen koppelen aan leeftijd en behandelkeuze.',
      ['fronting', 'stopping', 'devoicing', 'clusterreductie', 'syllabereductie', 'finale consonantdeletie'],
      'Een kind van 5 jaar zegt “tee” voor “kees” en laat clusters weg. Wat benoem je en waarom is leeftijd belangrijk?',
      'Leg uit hoe vereenvoudigingsprocessen je behandelprioriteit sturen.',
      'Ik benoem het proces, bijvoorbeeld fronting of clusterreductie, en weeg leeftijd en verstaanbaarheid. Bij hardnekkige processen kies ik doelen die functionele contrasten herstellen en de verstaanbaarheid verbeteren, niet zomaar losse klanken oefenen.',
      ['fronting', 'stopping', 'clusterreductie', 'leeftijd', 'verstaanbaarheid']
    ),
    lesson(
      'vod-consistentie',
      '15. Consistentie, VOD en planning',
      'Spraak',
      ['VOD', 'consistentie', 'planning'],
      'Veel wisselende fouten, zoekgedrag en moeite met sequenties kunnen wijzen op planning/programmering in plaats van één losse klankfout.',
      'Je moet herhaalde benoeming, stimulabiliteit en motorische planning meenemen voordat je methode kiest.',
      ['wisselende fouten', 'zoekgedrag', 'sequenties', 'consistentie-check', 'motorisch leren'],
      'Een kind zegt hetzelfde woord drie keer anders. Waarom verandert dit je differentiaaldiagnose?',
      'Leg uit waarom VOD anders behandeld wordt dan een fonologisch contrastprobleem.',
      'Bij wisselende fouten en zoekgedrag denk ik aan planning/programmering. Ik onderzoek consistentie en sequenties, omdat VOD intensieve motorische oefening en multisensorische cues vraagt. Alleen minimale paren zijn dan onvoldoende als hoofdroute.',
      ['vod', 'consistentie', 'planning', 'zoekgedrag', 'motorisch', 'sequentie']
    ),
    lesson(
      'behandeling-doelen',
      '16. Behandeldoelen en methodekeuze',
      'Behandeling',
      ['LT-doel', 'KT-doel', 'methode'],
      'Een behandelplan loopt van diagnose en ICF naar LT-doel, KT-doel, methode, vorm, duur, samenwerking en prognose.',
      'Doelen moeten SMART zijn en logisch optellen naar participatie.',
      ['LT-doel op participatie', 'KT-doel meetbaar', 'methode past bij probleemmechanisme', 'evaluatie', 'generalisatie'],
      'Een kind heeft clusterreductie en lage verstaanbaarheid. Formuleer een KT-doel dat bij een LT-participatiedoel past.',
      'Leg uit hoe je methodekeuze verantwoordt vanuit diagnose.',
      'Ik kies een methode pas na het probleemmechanisme. Een LT-doel richt zich op participatie, bijvoorbeeld beter meedoen in de klas. Een KT-doel is meetbaar op functieniveau, bijvoorbeeld een clustercontrast in 8 van 10 woorden. De methode past bij fonologisch, fonetisch, taalstructureel of spraakmotorisch probleem.',
      ['lt', 'kt', 'smart', 'methode', 'participatie', 'generalisatie']
    ),
    lesson(
      'icf-samenwerken',
      '17. ICF, samenwerking en prognose',
      'Behandeling',
      ['ICF', 'samenwerking', 'prognose'],
      'ICF maakt de brug van functie naar activiteit en participatie. Samenwerking borgt transfer; prognose weegt bevorderende en belemmerende factoren.',
      'Een sterk antwoord noemt niet alleen therapie, maar ook ouders, school, andere disciplines, evaluatiemoment en prognosevoorwaarden.',
      ['functie-activiteit-participatie', 'ouders en school', 'MDO', 'evaluatie', 'prognosefactoren'],
      'Een kind oefent goed in therapie maar gebruikt de vaardigheid niet in de klas. Wat ontbreekt in je plan?',
      'Maak een ICF-brug en koppel die aan samenwerking en prognose.',
      'Ik vertaal de functiestoornis naar activiteit en participatie. Daarna plan ik transfer via ouders en leerkracht, omdat therapiewinst pas betekenisvol is in dagelijks functioneren. Mijn prognose hangt af van ernst, leerbaarheid, omgeving, motivatie en comorbiditeit.',
      ['icf', 'participatie', 'ouders', 'school', 'samenwerking', 'prognose']
    ),
    lesson(
      'mondgebied-omft',
      '18. Mondgebied, OMFT en afwijkende mondgewoonten',
      'Mondgebied',
      ['OMFT', 'mondgewoonten', 'occlusie'],
      'Mondgewoonten, rustpositie, slikken, lipsluiting, tongpositie en occlusie kunnen spraak en behandeling beïnvloeden.',
      'Je moet structuur en functie onderscheiden en weten wanneer samenwerking met tandarts, orthodontist of arts nodig is.',
      ['structuuronderzoek', 'functieonderzoek', 'open beet', 'tongpersen', 'mondademen', 'triangle of forces'],
      'Een kind slist en heeft een open beet met duimzuiggeschiedenis. Waarom start je niet alleen met /s/-training?',
      'Leg uit waarom OMFT vaak eerst voorwaarden voor spraaktherapie herstelt.',
      'Bij afwijkende mondgewoonten behandel ik niet alleen de klank. Een open beet of tongpers kan de articulatie blijven verstoren. Daarom kijk ik naar rustpositie, slik, lipsluiting en gewoonteafbouw, en stem ik zo nodig af met tandarts of orthodontist.',
      ['omft', 'open beet', 'tong', 'slikken', 'mondgewoonte', 'orthodontist']
    )
  ]
};

function lesson(id, title, domain, tags, summary, snap, memory, caseQuestion, oralPrompt, model, checks) {
  return { id, title, domain, tags, summary, snap, memory, caseQuestion, oralPrompt, model, checks };
}
